/*
 * This source file was generated by the Gradle 'init' task
 */
package vsctemplatemc;

import org.bukkit.plugin.java.JavaPlugin;

public class App extends JavaPlugin {

    @Override
    public void onEnable() {

    }

    @Override
    public void onDisable() {

    }
}
